# Generated by Django 6.0 on 2026-04-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_category_remove_sanpham_danh_muc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã SKU')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá bán')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh chính')),
                ('stock', models.IntegerField(default=100, verbose_name='Tồn kho')),
                ('spec_power', models.CharField(blank=True, max_length=100, verbose_name='Công suất lọc')),
                ('spec_technology', models.CharField(blank=True, max_length=100, verbose_name='Công nghệ lọc')),
                ('spec_dimensions', models.CharField(blank=True, max_length=100, verbose_name='Kích thước')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật (Trang chủ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Danh sách sản phẩm',
            },
        ),
    ]
