# Generated by Django 6.0 on 2026-04-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Mô tả ngắn'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_bao_hanh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thời gian bảo hành'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_dung_tich',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dung tích bình'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_khoi_luong',
            field=models.CharField(blank=True, max_length=50, verbose_name='Khối lượng'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_loai_may',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loại máy'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_nam_ra_mat',
            field=models.CharField(blank=True, max_length=50, verbose_name='Năm ra mắt'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_nguon_nuoc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loại nguồn nước'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_nhiet_do_lanh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nhiệt độ lạnh'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_nhiet_do_nong',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nhiệt độ nóng'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_noi_san_xuat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nơi sản xuất'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_so_loi_loc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số lõi lọc'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_thong_so_khac',
            field=models.TextField(blank=True, verbose_name='Thông số khác'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_tinh_nang',
            field=models.TextField(blank=True, verbose_name='Tính năng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh chính'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL hình ảnh')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Chú thích')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh chi tiết',
                'verbose_name_plural': 'Thư viện ảnh sản phẩm',
            },
        ),
    ]
