# Generated by Django 6.0 on 2026-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_short_description_product_spec_bao_hanh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Hình ảnh chi tiết'),
        ),
    ]
