# Generated by Django 6.0 on 2026-04-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spec_dung_tich',
            new_name='spec_capacity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_nhiet_do_lanh',
            new_name='spec_cold_temp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_tinh_nang',
            new_name='spec_features',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_so_loi_loc',
            new_name='spec_filters_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_nhiet_do_nong',
            new_name='spec_hot_temp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_noi_san_xuat',
            new_name='spec_origin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_thong_so_khac',
            new_name='spec_other',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_nam_ra_mat',
            new_name='spec_release_year',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_loai_may',
            new_name='spec_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_bao_hanh',
            new_name='spec_warranty',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_nguon_nuoc',
            new_name='spec_water_source',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_khoi_luong',
            new_name='spec_weight',
        ),
    ]
