# Generated by Django 6.0 on 2026-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_spec_dung_tich_product_spec_capacity_and_more'),
    ]

    operations = [
        # Add index on Product.is_featured for homepage queries
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='product_featured_idx'),
        ),
        # Add index on Product.is_active for visibility filtering
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_active_idx'),
        ),
    ]
