# Generated by Django 6.0 on 2026-04-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_idx',
        ),
    ]
