# Generated by Django 6.0 on 2026-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_product_featured_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Ảnh chi tiết'), ('specs', 'Ảnh thông số'), ('features', 'Ảnh tính năng'), ('description', 'Ảnh mô tả chi tiết')], default='gallery', max_length=20, verbose_name='Loại hình ảnh'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Hình ảnh'),
        ),
    ]
