# Generated by Django 6.0 on 2026-05-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_image_type_alter_productimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
