# Generated by Django 6.0 on 2026-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_description',
            field=models.ImageField(blank=True, null=True, upload_to='products/description/', verbose_name='Ảnh mô tả chi tiết'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_features',
            field=models.ImageField(blank=True, null=True, upload_to='products/features/', verbose_name='Ảnh tính năng'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_specs',
            field=models.ImageField(blank=True, null=True, upload_to='products/specs/', verbose_name='Ảnh thông số'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Ảnh chi tiết')], default='gallery', max_length=20, verbose_name='Loại hình ảnh'),
        ),
    ]
