# Generated by Django 6.0 on 2026-05-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image_description_product_image_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_type',
        ),
    ]
