# Generated by Django 6.0 on 2026-05-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productimage_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_specs',
        ),
    ]
