# Generated by Django 6.0 on 2026-03-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quanlydanhmuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonDatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_hang', models.CharField(max_length=30, unique=True, verbose_name='Mã đơn hàng')),
                ('ngay_dat_don', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt đơn')),
                ('ho_ten', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('so_dien_thoai', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(verbose_name='Địa chỉ')),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_giao_hang', 'Đang giao hàng'), ('giao_hang_thanh_cong', 'Giao hàng thành công'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=30, verbose_name='Trạng thái')),
                ('hinh_thuc_thanh_toan', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản'), ('the_tin_dung', 'Thẻ tín dụng')], default='tien_mat', max_length=20, verbose_name='Hình thức thanh toán')),
                ('trang_thai_thanh_toan', models.CharField(choices=[('chua_thanh_toan', 'Chưa thanh toán'), ('da_thanh_toan', 'Đã thanh toán')], default='chua_thanh_toan', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('tien_coc', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tiền cọc')),
                ('nhan_vien_phu_trach', models.CharField(blank=True, max_length=200, verbose_name='Nhân viên phụ trách')),
            ],
            options={
                'verbose_name': 'Đơn đặt hàng',
                'verbose_name_plural': 'Đơn đặt hàng',
                'ordering': ['-ngay_dat_don'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Đơn giá')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlydanhmuc.sanpham', verbose_name='Sản phẩm')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlydondathang.dondathang', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
    ]
