# Generated by Django 6.0 on 2026-04-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_selected',
        ),
    ]
