# Generated by Django 6.0 on 2026-04-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhiemVuLapDat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhan_vien_ky_thuat', models.CharField(max_length=200, verbose_name='Nhân viên kỹ thuật')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_hoan_thanh', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_lap_dat', 'Chưa lắp đặt'), ('dang_xu_ly', 'Đang xử lý'), ('da_lap_dat', 'Đã lắp đặt')], default='cho_lap_dat', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhiem_vu', to='orders.dondathang')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ lắp đặt',
                'verbose_name_plural': 'Nhiệm vụ lắp đặt',
            },
        ),
    ]
