# Generated by Django 6.0 on 2026-04-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_chitietdonhang_don_hang_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200, verbose_name='Nhân viên kỹ thuật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chưa lắp đặt'), ('in_progress', 'Đang xử lý'), ('completed', 'Đã lắp đặt')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_task', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ lắp đặt',
                'verbose_name_plural': 'Quản lý lắp đặt',
            },
        ),
        migrations.DeleteModel(
            name='NhiemVuLapDat',
        ),
    ]
