# Generated by Django 6.0 on 2026-04-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_installationtask_delete_nhiemvulapdat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationtask',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='installationtask',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách'),
        ),
    ]
