# Generated by Django 6.0 on 2026-04-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_installationtask_staff_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstallationTask',
        ),
    ]
