# Generated by Django 6.0 on 2026-04-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10, verbose_name='Giới tính')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('rank', models.CharField(default='Classic', max_length=50, verbose_name='Hạng thành viên')),
                ('points', models.IntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Dữ liệu khách hàng',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('address_detail', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('address_type', models.CharField(choices=[('home', 'Nhà riêng/Chung cư'), ('office', 'Văn phòng'), ('other', 'Khác')], default='home', max_length=20, verbose_name='Loại địa chỉ')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Số địa chỉ',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
