# Generated by Django 6.0 on 2026-05-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='rank',
        ),
    ]
