# Generated by Django 6.0 on 2026-04-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khuyen_mai', models.CharField(max_length=255, verbose_name='Tên khuyến mãi')),
                ('ma_khuyen_mai', models.CharField(max_length=50, unique=True, verbose_name='Mã khuyến mãi')),
                ('dieu_kien_ap_dung', models.TextField(blank=True, verbose_name='Điều kiện áp dụng')),
                ('hinh_thuc_ap_dung', models.CharField(choices=[('phan_tram', 'Phần trăm'), ('gia_co_dinh', 'Giá cố định')], default='phan_tram', max_length=20, verbose_name='Hình thức áp dụng')),
                ('gia_tri', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá trị')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('san_pham_ap_dung', models.ManyToManyField(blank=True, to='categories.sanpham', verbose_name='Sản phẩm áp dụng')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
            },
        ),
    ]
