# Generated by Django 6.0 on 2026-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khuyến mãi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã khuyến mãi')),
                ('condition', models.TextField(blank=True, verbose_name='Điều kiện áp dụng')),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm'), ('fixed', 'Giá cố định')], default='percent', max_length=20, verbose_name='Hình thức')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Sản phẩm áp dụng')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Quản lý khuyến mãi',
            },
        ),
        migrations.DeleteModel(
            name='KhuyenMai',
        ),
    ]
