# Generated by Django 6.0 on 2026-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_delete_khuyenmai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='condition',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Điều kiện áp dụng (Giá tối thiểu)'),
        ),
    ]
