# Generated by Django 6.0 on 2026-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotion_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Đã gửi thông báo'),
        ),
    ]
