# Generated by Django 6.0 on 2026-05-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promotion_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='code',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='condition',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=12, null=True, verbose_name='Điều kiện áp dụng (Giá tối thiểu)'),
        ),
    ]
