# Generated by Django 6.0 on 2026-04-14 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_danhmuc_options_alter_danhmuc_ma_danh_muc'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='home/banners/')),
                ('mutosi_pro_title', models.CharField(default='Mutosi Hydrogen Pro', max_length=255)),
                ('mutosi_pro_desc', models.TextField(default='Mutosi Pro mới, với công nghệ Hydrogen Pro vượt trội...')),
                ('mutosi_pro_highlight', models.CharField(default='Uống nước mỗi ngày - Khoẻ vượt kỳ vọng', max_length=255)),
                ('mutosi_pro_image', models.ImageField(blank=True, null=True, upload_to='home/brands/')),
                ('bottom_banner_image', models.ImageField(blank=True, null=True, upload_to='home/banners/')),
                ('bottom_cta_text', models.CharField(default='“Hãy đến và trải nghiệm sản phẩm Mutosi mới nhất...”', max_length=255)),
                ('category_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h_cat1', to='categories.danhmuc')),
                ('category_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h_cat2', to='categories.danhmuc')),
                ('featured_products', models.ManyToManyField(blank=True, to='categories.sanpham')),
            ],
            options={
                'verbose_name': 'Cài đặt Trang chủ',
                'verbose_name_plural': 'Cài đặt Trang chủ',
            },
        ),
    ]
