# Generated by Django 6.0 on 2026-04-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_remove_sanpham_danh_muc'),
        ('core', '0002_homepagesettings'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/banners/', verbose_name='Banner chính'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='bottom_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/banners/', verbose_name='Banner chân trang'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='bottom_cta_text',
            field=models.CharField(default='“Hãy đến và trải nghiệm sản phẩm Mutosi mới nhất...”', max_length=255, verbose_name='Thông điệp CTA'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='category_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h_cat1', to='categories.category', verbose_name='Danh mục nổi bật 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='category_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h_cat2', to='categories.category', verbose_name='Danh mục nổi bật 2'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='Sản phẩm đặc sắc'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='mutosi_pro_desc',
            field=models.TextField(default='Mutosi Pro mới, với công nghệ Hydrogen Pro vượt trội...', verbose_name='Mô tả Mutosi Pro'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='mutosi_pro_highlight',
            field=models.CharField(default='Uống nước mỗi ngày - Khoẻ vượt kỳ vọng', max_length=255, verbose_name='Điểm nhấn'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='mutosi_pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/brands/', verbose_name='Ảnh Mutosi Pro'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='mutosi_pro_title',
            field=models.CharField(default='Mutosi Hydrogen Pro', max_length=255, verbose_name='Tiêu đề Mutosi Pro'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
