# Generated by Django 6.0 on 2026-04-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_address_remove_customer_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Các thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
