# Generated by Django 6.0 on 2026-04-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='warranty_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Ảnh nền trang bảo hành'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='warranty_desc',
            field=models.TextField(default='Dahuka cam kết mang đến dịch vụ bảo hành tận tâm và chuyên nghiệp nhất.', verbose_name='Mô tả trang bảo hành'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='warranty_title',
            field=models.CharField(default='TRA CỨU THÔNG TIN BẢO HÀNH', max_length=255, verbose_name='Tiêu đề trang bảo hành'),
        ),
    ]
