# Generated by Django 6.0 on 2026-04-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepagesettings_warranty_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='warranty_banner',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='warranty_desc',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='warranty_title',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='warranty_img_service',
            field=models.ImageField(blank=True, null=True, upload_to='warranty/', verbose_name='Ảnh Dịch vụ Dahuka'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='warranty_img_store',
            field=models.ImageField(blank=True, null=True, upload_to='warranty/', verbose_name='Ảnh Điểm bán Dahuka'),
        ),
    ]
