# Generated by Django 6.0 on 2026-04-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_homepagesettings_warranty_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='warranty_img_service',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='warranty_img_store',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='warranty_image_one',
            field=models.ImageField(blank=True, null=True, upload_to='warranty/', verbose_name='Ảnh Bảo hành 1 (Thẻ chính)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='warranty_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='warranty/', verbose_name='Ảnh Bảo hành 2 (Dịch vụ)'),
        ),
    ]
