# Generated by Django 6.0 on 2026-05-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_homepagesettings_warranty_img_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='warranty_image_one',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='warranty_image_two',
        ),
    ]
