# Generated by Django 6.0 on 2026-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_homepagesettings_warranty_image_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesettings',
            old_name='mutosi_pro_highlight',
            new_name='dahuka_pro_highlight',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='mutosi_pro_desc',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='mutosi_pro_image',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='mutosi_pro_title',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='dahuka_pro_desc',
            field=models.TextField(default='Dahuka Pro mới, với công nghệ Hydrogen Pro vượt trội...', verbose_name='Mô tả Dahuka Pro'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='dahuka_pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/brands/', verbose_name='Ảnh Dahuka Pro'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='dahuka_pro_title',
            field=models.CharField(default='Dahuka Hydrogen Pro', max_length=255, verbose_name='Tiêu đề Dahuka Pro'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='bottom_cta_text',
            field=models.CharField(default='“Hãy đến và trải nghiệm sản phẩm Dahuka mới nhất...”', max_length=255, verbose_name='Thông điệp CTA'),
        ),
    ]
