# Generated by Django 6.0 on 2026-04-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_chitietdonhang_don_hang_and_more'),
        ('tasks', '0002_installationtask_delete_nhiemvulapdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonDatHang',
        ),
        migrations.DeleteModel(
            name='ChiTietDonHang',
        ),
    ]
