# Generated by Django 6.0 on 2026-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_dondathang_delete_chitietdonhang'),
    ]

    operations = [
        # Add index on Order.status for frequent filtering
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        # Add composite index for customer + created_at (common query pattern)
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='order_customer_date_idx'),
        ),
    ]
