# Generated by Django 6.0 on 2026-04-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_customer_date_idx',
        ),
    ]
