# Generated by Django 6.0 on 2026-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='order',
            name='house_details',
            field=models.CharField(blank=True, max_length=255, verbose_name='Số nhà, tên đường'),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã'),
        ),
    ]
