# Generated by Django 6.0 on 2026-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_address_order_city_order_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hinh_thuc_thanh_toan',
            field=models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản')], default='chuyen_khoan', max_length=20, verbose_name='Hình thức thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='trang_thai_thanh_toan',
            field=models.CharField(choices=[('chua_thanh_toan', 'Chưa thanh toán'), ('da_thanh_toan', 'Đã thanh toán')], default='chua_thanh_toan', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
    ]
