# Generated by Django 6.0 on 2026-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_hinh_thuc_thanh_toan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do hủy'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú của khách hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_proofs/', verbose_name='Ảnh minh chứng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang giao'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
