# Generated by Django 6.0 on 2026-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_cancel_reason_order_note_order_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='warranty_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn bảo hành'),
        ),
    ]
