# Generated by Django 6.0 on 2026-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_order_code_order_warranty_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warranty_expiration',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warranty_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn bảo hành'),
        ),
    ]
