# Generated by Django 6.0 on 2026-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_warranty_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền cọc'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hinh_thuc_thanh_toan',
            field=models.CharField(choices=[('full', 'Thanh toán toàn bộ'), ('deposit', 'Thanh toán cọc')], default='full', max_length=20, verbose_name='Hình thức thanh toán'),
        ),
    ]
