# Generated by Django 6.0 on 2026-04-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hinh_thuc_thanh_toan',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='trang_thai_thanh_toan',
            new_name='payment_status',
        ),
    ]
