# Generated by Django 6.0 on 2026-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhmuc',
            options={'ordering': ['id'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ma_danh_muc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã danh mục'),
        ),
    ]
