# Generated by Django 6.0 on 2026-04-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_category_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
    ]
