# Generated by Django 6.0 on 2026-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Ảnh biểu tượng')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='categories/banners/', verbose_name='Ảnh banner')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục sản phẩm',
            },
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='danh_muc',
        ),
    ]
