# Generated by Django 6.0 on 2026-05-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
    ]
