# Generated by Django 6.0 on 2026-04-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_remove_sanpham_danh_muc'),
        ('core', '0003_remove_order_address_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DanhMuc',
        ),
    ]
