# Generated by Django 6.0 on 2026-04-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_delete_danhmuc'),
        ('core', '0003_remove_order_address_remove_customer_user_and_more'),
        ('orders', '0002_remove_chitietdonhang_don_hang_and_more'),
        ('promotions', '0002_promotion_delete_khuyenmai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SanPham',
        ),
    ]
