# Generated by Django 6.0 on 2026-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_delete_sanpham'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã danh mục'),
        ),
    ]
