# Generated by Django 6.0 on 2026-03-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_danh_muc', models.CharField(max_length=20, unique=True, verbose_name='Mã danh mục')),
                ('ten_danh_muc', models.CharField(max_length=200, verbose_name='Tên danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['ma_danh_muc'],
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_san_pham', models.CharField(max_length=20, unique=True, verbose_name='Mã sản phẩm')),
                ('ten_san_pham', models.CharField(max_length=300, verbose_name='Tên sản phẩm')),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá tiền')),
                ('ton_kho', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('trang_thai_hien_thi', models.BooleanField(default=True, verbose_name='Trạng thái hiển thị')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlydanhmuc.danhmuc', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['ma_san_pham'],
            },
        ),
    ]
