# Generated by Django 6.0 on 2026-04-19 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_productimage_image_type_alter_productimage_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Số Serial')),
                ('activated_date', models.DateField(blank=True, null=True, verbose_name='Ngày kích hoạt')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('is_active', models.BooleanField(default=False, verbose_name='Trạng thái kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Thẻ bảo hành',
                'verbose_name_plural': 'Quản lý bảo hành',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày bảo trì')),
                ('work_done', models.TextField(verbose_name='Nội dung thực hiện')),
                ('technician', models.CharField(max_length=255, verbose_name='Kỹ thuật viên')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Hẹn bảo trì tiếp theo')),
                ('warranty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='warranty.warrantycard', verbose_name='Thẻ bảo hành')),
            ],
            options={
                'verbose_name': 'Lịch sử bảo trì',
                'verbose_name_plural': 'Lịch sử bảo trì',
            },
        ),
    ]
