# Generated by Django 6.0 on 2026-04-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Máy lọc nước Dahuka', max_length=255, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(default='644 Nguyễn Hữu Thọ, Khuê Trung, Cẩm Lệ, Đà Nẵng', max_length=255, verbose_name='Địa chỉ')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='warranty/', verbose_name='Ảnh bản đồ')),
                ('hotline1', models.CharField(default='0814 468 131', max_length=50, verbose_name='Hotline 1 (Zalo)')),
                ('hotline2', models.CharField(default='0822 493 134', max_length=50, verbose_name='Hotline 2')),
                ('working_hours', models.CharField(default='8h00 - 21h00 (T2 - CN)', max_length=100, verbose_name='Giờ làm việc')),
            ],
            options={
                'verbose_name': 'Cấu hình trang bảo hành',
                'verbose_name_plural': 'Cấu hình trang bảo hành',
            },
        ),
    ]
