# Generated by Django 6.0 on 2026-04-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_warrantypagesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='warranty_card',
        ),
        migrations.RemoveField(
            model_name='warrantycard',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='warrantycard',
            name='product',
        ),
        migrations.DeleteModel(
            name='WarrantyPageSettings',
        ),
        migrations.DeleteModel(
            name='MaintenanceHistory',
        ),
        migrations.DeleteModel(
            name='WarrantyCard',
        ),
    ]
