# Generated by Django 6.0 on 2026-04-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warranty', '0003_remove_maintenancehistory_warranty_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Điểm bán - Bảo hành', max_length=255, verbose_name='Tiêu đề trang')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='warranty/', verbose_name='Ảnh minh họa 1')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='warranty/', verbose_name='Ảnh minh họa 2')),
                ('store_location_title', models.CharField(default='Vị trí cửa hàng', max_length=255, verbose_name='Tiêu đề Vị trí')),
                ('online_contact_title', models.CharField(default='Liên hệ trực tuyến', max_length=255, verbose_name='Tiêu đề Liên hệ')),
            ],
            options={
                'verbose_name': 'Cài đặt Trang Bảo hành',
                'verbose_name_plural': 'Cài đặt Trang Bảo hành',
            },
        ),
    ]
